/**
 * Asset entity shapes — mirrors public.assets table.
 * Server-side only; shared with client via API responses.
 */
import type { ApiError } from '@/lib/api-response';

export type AssetType = 'audio' | 'video';
export type AssetStatus = 'draft' | 'published';
export type UserRole = 'admin' | 'user';

export interface Asset {
  id: string;
  title: string;
  description: string | null;
  category_id: string | null;
  asset_type: AssetType;
  status: AssetStatus;
  file_key: string;
  file_size_bytes: number;
  mime_type: string;
  duration_seconds: number | null;
  download_url: string | null;
  thumbnail_url: string | null;
  tags: string[];
  download_count: number;
  view_count: number;
  uploaded_by: string;
  created_at: string;
  updated_at: string;
  published_at: string | null;
  is_featured: boolean;
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  icon: string | null;
  sort_order: number;
  created_at: string;
}

export interface Profile {
  id: string;
  email: string;
  display_name: string | null;
  avatar_url: string | null;
  role: UserRole;
  created_at: string;
}

export interface Favorite {
  id: string;
  user_id: string;
  asset_id: string;
  created_at: string;
}

export interface DownloadLog {
  id: string;
  asset_id: string;
  user_id: string | null;
  ip_address: string;
  user_agent: string | null;
  created_at: string;
}

/**
 * Asset with optional category (populated by API routes via select=*)
 */
export interface AssetWithCategory extends Asset {
  category?: Category | null;
  /**
   * On-the-fly presigned GET URL for inline preview (expire 1 hour).
   * Generated by GET /api/assets/[id]; not persisted to DB.
   */
  preview_url?: string | null;
}

/**
 * API response envelope — used by every route.
 */
export interface ApiResponse<T = unknown> {
  data: T | null;
  error: string | ApiError | null;
}
